[workspace]
members = [
    "contracts/simple-counter",
    "contracts/treasury",
    "interact",
    "colony-chain"
]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true