name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lints:
    name: rustfmt & clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test in interact
        working-directory: interact
        run: cargo test

      - name: Run cargo test in simple counter
        working-directory: contracts/simple-counter
        run: cargo unit-test

  build:
    name: cargo build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown

      - name: build interact
        working-directory: interact
        run: cargo build

      - name: build simple-counter
        working-directory: contracts/simple-counter
        run: cargo wasm

      - name: build schema for simple-counter
        working-directory: contracts/simple-counter
        run: cargo schema
